-- migrate:up
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (1, 'Chavez, Page and Gonzalez', 38);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (2, 'Bryant-Crawford', 84);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (3, 'Chambers LLC', 81);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (4, 'Lowe, Huff and Taylor', 65);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (5, 'Melton Inc', 47);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (6, 'Hernandez-Murphy', 46);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (7, 'Jackson-Myers', 49);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (8, 'Oliver LLC', 10);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (9, 'Ramirez-Aguirre', 12);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (10, 'Cowan-Stephens', 86);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (11, 'Yu-Medina', 51);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (12, 'Carter Inc', 79);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (13, 'Mcguire LLC', 75);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (14, 'Hancock Ltd', 67);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (15, 'Parker, Miles and Newman', 16);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (16, 'Savage, White and Bennett', 77);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (17, 'Fleming-Ryan', 62);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (18, 'Williams Ltd', 22);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (19, 'Brewer PLC', 74);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (20, 'Cruz Ltd', 100);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (21, 'Boyle and Sons', 87);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (22, 'Vega-Haynes', 45);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (23, 'Clayton-Sanders', 5);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (24, 'Richards-Taylor', 3);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (25, 'Smith, Wilson and Guzman', 50);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (26, 'Joseph and Sons', 96);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (27, 'Hughes and Sons', 63);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (28, 'Lawson, Morrison and Price', 91);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (29, 'Wilson Ltd', 17);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (30, 'Rogers-Brown', 80);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (31, 'Dixon, Golden and Vazquez', 56);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (32, 'Abbott-Doyle', 73);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (33, 'Wilkinson, Murray and Cochran', 90);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (34, 'Ortega-Short', 76);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (35, 'Becker Group', 35);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (36, 'Bird, Bridges and Camacho', 23);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (37, 'Harris Group', 40);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (38, 'Costa, Rodriguez and Johns', 39);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (39, 'Ware-Kelly', 7);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (40, 'Gates Group', 44);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (41, 'Wilson PLC', 55);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (42, 'Shah-Hodge', 14);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (43, 'Foley Ltd', 36);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (44, 'Williamson, Silva and Davis', 20);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (45, 'Clay-Allen', 88);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (46, 'Barry, Smith and Ramirez', 97);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (47, 'Stone-Ford', 13);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (48, 'Martinez Inc', 25);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (49, 'Nichols-Smith', 66);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (50, 'Erickson and Sons', 31);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (51, 'Wilkins LLC', 82);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (52, 'Bryan-Willis', 21);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (53, 'Mclean-Griffith', 95);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (54, 'Howell and Sons', 70);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (55, 'Miller and Sons', 54);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (56, 'Cooper-Hall', 92);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (57, 'James, Kennedy and Scott', 57);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (58, 'Johnson, Duke and Thomas', 37);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (59, 'Parks-Harris', 27);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (60, 'Flores, Hill and Vasquez', 6);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (61, 'Reed, Gibson and Reed', 89);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (62, 'Mitchell LLC', 43);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (63, 'James-Townsend', 15);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (64, 'Li Inc', 71);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (65, 'Martinez PLC', 61);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (66, 'Evans-Walker', 11);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (67, 'Pierce-Chavez', 59);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (68, 'Turner Ltd', 1);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (69, 'Black-Shah', 53);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (70, 'Mcdaniel, Armstrong and Gonzalez', 93);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (71, 'Guerrero Ltd', 69);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (72, 'Charles, Hart and Harrell', 72);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (73, 'Blevins, Fox and Wang', 33);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (74, 'Callahan, Burton and Moreno', 28);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (75, 'Castro, Porter and Bennett', 58);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (76, 'Davis Ltd', 30);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (77, 'Marshall PLC', 64);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (78, 'Carter Group', 83);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (79, 'Smith Group', 98);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (80, 'Wilson-Miller', 32);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (81, 'Hansen, Hull and Hahn', 24);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (82, 'Edwards Ltd', 19);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (83, 'Martinez-Newton', 68);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (84, 'Watkins Inc', 29);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (85, 'Lee, Brown and Horne', 8);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (86, 'Mathis-Avila', 60);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (87, 'Quinn-Hernandez', 26);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (88, 'Clay Group', 99);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (89, 'Miller-Braun', 48);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (90, 'Garcia, Brooks and Best', 41);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (91, 'Johnston-Smith', 9);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (92, 'Howard, Hicks and Martinez', 85);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (93, 'Lewis, Smith and Garcia', 52);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (94, 'Mccann-Miller', 4);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (95, 'Miller-Quinn', 34);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (96, 'Nguyen, Weaver and Curry', 18);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (97, 'Parker, Jordan and Mercado', 42);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (98, 'Martinez PLC', 94);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (99, 'Buchanan-Torres', 2);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (100, 'Williams Ltd', 78);


-- migrate:down

