INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (1, 'Garcia-Castillo', 100);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (2, 'Rodriguez, Todd and Baldwin', 80);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (3, 'Perkins, Floyd and Chang', 27);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (4, 'Bell and Sons', 89);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (5, 'Valencia, Chambers and Moore', 76);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (6, 'Walker-White', 88);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (7, 'Ramos-Monroe', 87);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (8, 'Chapman, Garcia and Mullins', 47);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (9, 'King-Martinez', 36);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (10, 'Wilson, Maynard and Marshall', 52);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (11, 'Cruz, Jones and Collins', 37);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (12, 'Lin Group', 7);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (13, 'Schmitt-Mathews', 14);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (14, 'Mills Inc', 6);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (15, 'Crane, Lopez and Murray', 93);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (16, 'Beltran PLC', 86);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (17, 'Marsh-Scott', 96);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (18, 'Benton Ltd', 28);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (19, 'Tucker Inc', 33);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (20, 'Nicholson-Ruiz', 74);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (21, 'Hawkins, Cooper and Goodwin', 98);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (22, 'Vega Ltd', 26);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (23, 'Hart-Wells', 66);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (24, 'Contreras and Sons', 78);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (25, 'Chase, Boyd and Liu', 70);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (26, 'Flowers-Bernard', 48);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (27, 'Fisher, Howe and Wallace', 53);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (28, 'Park-Spencer', 10);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (29, 'Vazquez, Hood and Ingram', 84);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (30, 'Garcia Group', 81);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (31, 'Rowe, Taylor and Flores', 11);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (32, 'Brown-Silva', 40);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (33, 'Davis, Arnold and Ellis', 83);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (34, 'Kent, Clayton and Perez', 82);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (35, 'Taylor and Sons', 62);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (36, 'Jones-Simpson', 17);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (37, 'Coleman, Tran and Bryan', 38);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (38, 'Williams-Dougherty', 68);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (39, 'Warner, Weaver and Rowland', 29);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (40, 'Miller, Forbes and Carpenter', 15);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (41, 'King, Owens and Lee', 90);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (42, 'Moore PLC', 94);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (43, 'Alexander LLC', 85);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (44, 'Rivera-Lucas', 34);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (45, 'Russell, Robinson and Sharp', 55);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (46, 'Adams-Gardner', 60);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (47, 'Woods, Smith and Aguirre', 20);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (48, 'Serrano LLC', 39);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (49, 'Oliver, Roberts and Humphrey', 23);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (50, 'Munoz-Johnson', 25);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (51, 'Flores-Sanders', 43);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (52, 'Austin, Peterson and Butler', 56);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (53, 'Cruz Group', 46);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (54, 'Barajas PLC', 30);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (55, 'Reyes Ltd', 9);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (56, 'Martin, Harris and Garcia', 61);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (57, 'Martin, Rosales and James', 51);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (58, 'Ware-Gray', 8);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (59, 'Graham and Sons', 79);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (60, 'Smith PLC', 97);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (61, 'Perez-Williams', 71);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (62, 'Hurst-Whitney', 57);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (63, 'Ruiz, Kelly and Salazar', 65);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (64, 'Mathews-Wilson', 41);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (65, 'Fowler Group', 22);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (66, 'Price-Jacobson', 91);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (67, 'Miller-Yates', 69);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (68, 'Sanchez LLC', 92);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (69, 'Olson-Martin', 32);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (70, 'Mcclain, Bradley and Bates', 4);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (71, 'Rodriguez-Reed', 13);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (72, 'Smith, Cruz and Sweeney', 3);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (73, 'Davis-Smith', 12);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (74, 'Thompson-Anderson', 18);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (75, 'Rodriguez, Castro and Ward', 77);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (76, 'Romero-Hunt', 42);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (77, 'Arnold-Barton', 67);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (78, 'Owens-Bautista', 5);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (79, 'Sanchez-Mckay', 44);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (80, 'Black and Sons', 75);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (81, 'Pineda-Chavez', 73);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (82, 'Reynolds, Frey and White', 45);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (83, 'Torres-Anderson', 58);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (84, 'Cochran, Lewis and Guerra', 95);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (85, 'Walsh-Rivera', 2);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (86, 'Serrano and Sons', 49);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (87, 'Robinson-Allen', 1);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (88, 'White PLC', 54);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (89, 'Phillips, Espinoza and Manning', 31);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (90, 'Green, Waller and Carroll', 16);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (91, 'Ortega-Wilson', 64);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (92, 'Moore, Koch and Clark', 59);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (93, 'Gill Ltd', 21);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (94, 'Hernandez, Mathews and Morrison', 72);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (95, 'Jones PLC', 99);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (96, 'Larson-Spence', 35);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (97, 'Roach-Joseph', 50);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (98, 'Chavez Ltd', 24);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (99, 'Mcdonald PLC', 63);
INSERT INTO organizaciones (id, nombre, profesor_id) VALUES (100, 'Hampton Ltd', 19);
