INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (1, 'Introducción a la fotografía digital', 9547, 'Detail choose occur color nothing chair. Style accept go staff best myself wall. Protect hope growth nation.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (2, 'Cocina internacional para principiantes', 5708, 'Attorney cold kind stay too option.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (3, 'Historia del arte moderno', 9204, 'Much become message guy. Near they yet feeling involve represent green.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (4, 'Fundamentos de la astronomía', 6722, 'Mouth seat artist. Agree professional animal tell executive. Involve middle they against on.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (5, 'Técnicas de meditación y mindfulness', 5876, 'Choice consumer to near alone evening. Worker society language water. Score us glass store.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (6, 'Diseño gráfico con adobe illustrator', 3054, 'They although hundred lead draw. Step media make. Large police city throughout part.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (7, 'Marketing en redes sociales', 4340, 'Audience technology money hundred artist before. Unit energy group federal population bank necessary. A claim instead decide discover hit.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (8, 'Escritura creativa y narrativa', 1286, 'Scientist house type member boy six summer. Beautiful television anyone want heart teacher machine. Mean employee serious world most yeah friend. Less sing wind ever.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (9, 'Introducción a la psicología', 3198, 'Child talk reveal person behavior animal. Performance who company claim life involve. Begin argue issue rest executive. Tree reason stuff explain.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (10, 'Música y producción de audio', 3567, 'Million unit ball something.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (11, 'Jardinería urbana y sostenible', 9645, 'Defense send myself. Television some career account list call fast. Adult almost early environment practice people.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (12, 'Principios de economía', 8399, 'Away soldier if model full bag specific. Place surface move huge. Million morning our against whose without. Safe age product everything.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (13, 'Cuidado y entrenamiento de mascotas', 6511, 'Language cover ability letter become soon. Until owner measure way.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (14, 'Introducción a la filosofía', 4501, 'Move for job. Toward look fish. Street hour pass serve score.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (15, 'Fotografía de naturaleza y paisajes', 2160, 'Check staff agree dark pick media. His rich state both.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (16, 'Diseño de interiores', 5978, 'Itself knowledge actually office.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (17, 'Cultura y civilización japonesa', 3459, 'Per knowledge such writer course. Fish within four shoulder population public.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (18, 'Técnicas de pintura al óleo', 5411, 'Language mind ready. Character ask stand among large. Area kind buy cell activity.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (19, 'Introducción a la programación en c++', 8074, 'Tonight difficult none fish understand together. Body story walk system marriage none expect require. Off wonder arm music technology.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (20, 'Yoga para principiantes', 4302, 'Other guy role small anything. Including car military character call. Become other view social politics prepare economy.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (21, 'Introducción a la programación', 7734, 'Community alone but everyone compare. Truth full she government. Set final participant lay office eight local. Region everyone seven.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (22, 'Diseño gráfico y multimedia', 5329, 'Rise understand service. Open be dog present to. Do although choice a read but both through.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (23, 'Marketing digital y redes sociales', 3920, 'At into whose marriage fly. Positive girl marriage whom.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (24, 'Desarrollo web y aplicaciones móviles', 2752, 'Hospital half check set. Available air class ago talk ten.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (25, 'Fotografía y edición de imágenes', 3333, 'Follow huge real appear economic. Idea issue fast pressure room operation. Food answer Democrat too think.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (26, 'Gestión de proyectos', 7898, 'Debate total successful market game listen.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (27, 'Finanzas personales y ahorro', 9064, 'Race my candidate. Their court third amount when.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (28, 'Cocina internacional', 2142, 'Fill north interest culture usually book. Away throughout able environment particular affect also.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (29, 'Idiomas: inglés, francés, alemán, etc.', 3316, 'Political floor say shake program. Your form over set history. Deal quickly effort seem course suffer side former.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (30, 'Mindfulness y meditación', 9277, 'Close research woman leg another poor system. Bag reach top factor against leave drug today.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (31, 'Emprendimiento y startups', 6749, 'Evening necessary speech edge camera country career. Everybody foreign view run.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (32, 'Ciberseguridad y protección de datos', 4502, 'Agent return weight century rule degree. Product top movement go tree myself.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (33, 'Redacción y escritura creativa', 2753, 'Major detail project create product evening professional beat. Performance defense difference with.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (34, 'Música y producción musical', 8495, 'Official research middle require order area term. Kid design dream character officer. Wear dinner still yourself lot.');
INSERT INTO cursos (id, nombre, codigo, descripcion) VALUES (35, 'Ciencias de la salud y nutrición', 3413, 'Admit size various win scientist rock.');
